version: '3.7'
services:
    db:
      image: postgres:14.4-alpine
      container_name: postgres
      restart: always
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./postgresql.conf:/etc/postgresql/postgresql.conf
      networks:
        - mylocal
    server:
      build: ./server
      container_name: chat
      ports:
        - ${SERVER_PORT}:${SERVER_PORT}
      restart: on-failure
      networks:
        - mylocal

networks:
  mylocal:
    driver: bridge